services:
  privana:
    build:
      context: .
      args:
        - ENV_FILE=.env.testnet
    image: "ghcr.io/oasisprotocol/privana@sha256:ba7a4ae692c169f90beda7fd2849cfd9365ed7c867d7d95e3f019478acf08414"
    platform: linux/amd64
    environment:
      - SWEEP_STATE_DIR=/data/sweep-engine
      - ONRAMP_PROVIDER
      - TRANSAK_CLIENT_IP_HEADER
      - ALCHEMY_API_KEY
      - MOONPAY_API_KEY
      - MOONPAY_SECRET_KEY
      - MOONPAY_WEBHOOK_SECRET_KEY
      - TRANSAK_API_KEY
      - TRANSAK_API_SECRET
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
      - sweep-engine-data:/data/sweep-engine
    ports:
      - "8000:8000"
    annotations:
      net.oasis.proxy.ports.8000.custom_domain: api.testnet.privana.finance
    restart: on-failure

volumes:
  sweep-engine-data:
