services:
  privana:
    build:
      context: .
      args:
        - ENV_FILE=.env.mainnet
    image: "ghcr.io/oasisprotocol/privana@sha256:a14f312989ae873ef5e6e4d3434e349a6159a17883ee098ae1b00937de028db8"
    platform: linux/amd64
    environment:
      - SWEEP_STATE_DIR=/data/sweep-engine
      - ONRAMP_PROVIDER
      - TRANSAK_CLIENT_IP_HEADER
      - TRANSAK_IP_ATTESTATION_SECRET
      - ALCHEMY_API_KEY
      - MOONPAY_API_KEY
      - MOONPAY_SECRET_KEY
      - MOONPAY_WEBHOOK_SECRET_KEY
      - TRANSAK_API_KEY
      - TRANSAK_API_SECRET
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
      - sweep-engine-data:/data/sweep-engine
    ports:
      - "8000:8000"
    annotations:
      net.oasis.proxy.ports.8000.custom_domain: api.privana.finance
    restart: on-failure

volumes:
  sweep-engine-data:
