"""Accounting module ABI."""

ACCOUNTING_ABI = [{'inputs': [], 'name': 'ECDSAInvalidSignature', 'type': 'error'},
 {'inputs': [{'internalType': 'uint256', 'name': 'length', 'type': 'uint256'}],
  'name': 'ECDSAInvalidSignatureLength',
  'type': 'error'},
 {'inputs': [{'internalType': 'bytes32', 'name': 's', 'type': 'bytes32'}],
  'name': 'ECDSAInvalidSignatureS',
  'type': 'error'},
 {'inputs': [], 'name': 'InvalidDeposit', 'type': 'error'},
 {'inputs': [], 'name': 'InvalidShortString', 'type': 'error'},
 {'inputs': [], 'name': 'InvalidSignature', 'type': 'error'},
 {'inputs': [{'internalType': 'string', 'name': 'str', 'type': 'string'}],
  'name': 'StringTooLong',
  'type': 'error'},
 {'anonymous': False,
  'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'indexed': True, 'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'indexed': False, 'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'}],
  'name': 'Deposit',
  'type': 'event'},
 {'anonymous': False, 'inputs': [], 'name': 'EIP712DomainChanged', 'type': 'event'},
 {'inputs': [{'internalType': 'address', 'name': 'user', 'type': 'address'},
             {'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'}],
  'name': 'balances',
  'outputs': [{'internalType': 'uint256', 'name': 'balance', 'type': 'uint256'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'internalType': 'bytes32', 'name': 'chainId', 'type': 'bytes32'}],
  'name': 'chains',
  'outputs': [{'internalType': 'enum ChainType', 'name': 'chainType', 'type': 'uint8'},
              {'internalType': 'bytes', 'name': 'chainIdentifier', 'type': 'bytes'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [],
  'name': 'eip712Domain',
  'outputs': [{'internalType': 'bytes1', 'name': 'fields', 'type': 'bytes1'},
              {'internalType': 'string', 'name': 'name', 'type': 'string'},
              {'internalType': 'string', 'name': 'version', 'type': 'string'},
              {'internalType': 'uint256', 'name': 'chainId', 'type': 'uint256'},
              {'internalType': 'address', 'name': 'verifyingContract', 'type': 'address'},
              {'internalType': 'bytes32', 'name': 'salt', 'type': 'bytes32'},
              {'internalType': 'uint256[]', 'name': 'extensions', 'type': 'uint256[]'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'components': [{'internalType': 'enum ChainType',
                              'name': 'chainType',
                              'type': 'uint8'},
                             {'internalType': 'bytes', 'name': 'chainIdentifier', 'type': 'bytes'}],
              'internalType': 'struct ChainInfo',
              'name': 'info',
              'type': 'tuple'}],
  'name': 'getChainId',
  'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
  'stateMutability': 'pure',
  'type': 'function'},
 {'inputs': [{'components': [{'internalType': 'bytes32', 'name': 'chainId', 'type': 'bytes32'},
                             {'internalType': 'bytes', 'name': 'tokenAddress', 'type': 'bytes'},
                             {'internalType': 'string', 'name': 'ticker', 'type': 'string'}],
              'internalType': 'struct TokenInfo',
              'name': 'info',
              'type': 'tuple'}],
  'name': 'getTokenId',
  'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
  'stateMutability': 'pure',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'internalType': 'bytes', 'name': 'evmTransactionData', 'type': 'bytes'},
             {'components': [{'internalType': 'bytes', 'name': 'rlpBlockHeader', 'type': 'bytes'},
                             {'internalType': 'bytes',
                              'name': 'transactionIndexRlp',
                              'type': 'bytes'},
                             {'internalType': 'bytes',
                              'name': 'transactionProofStack',
                              'type': 'bytes'}],
              'internalType': 'struct TransactionProof',
              'name': 'txProof',
              'type': 'tuple'}],
  'name': 'includeEVMErc20Deposit',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'internalType': 'bytes', 'name': 'evmTransactionData', 'type': 'bytes'},
             {'components': [{'internalType': 'bytes', 'name': 'rlpBlockHeader', 'type': 'bytes'},
                             {'internalType': 'bytes',
                              'name': 'transactionIndexRlp',
                              'type': 'bytes'},
                             {'internalType': 'bytes',
                              'name': 'transactionProofStack',
                              'type': 'bytes'}],
              'internalType': 'struct TransactionProof',
              'name': 'txProof',
              'type': 'tuple'}],
  'name': 'includeEVMNativeDeposit',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'address', 'name': 'serviceAddress', 'type': 'address'},
             {'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'expiry', 'type': 'uint256'},
             {'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
  'name': 'lockFunds',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'}],
  'name': 'tokens',
  'outputs': [{'internalType': 'bytes32', 'name': 'chainId', 'type': 'bytes32'},
              {'internalType': 'bytes', 'name': 'tokenAddress', 'type': 'bytes'},
              {'internalType': 'string', 'name': 'ticker', 'type': 'string'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'address', 'name': 'toAddress', 'type': 'address'},
             {'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'expiry', 'type': 'uint256'},
             {'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
  'name': 'transferFunds',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'uint256', 'name': 'lockIndex', 'type': 'uint256'},
             {'internalType': 'address', 'name': 'toAddress', 'type': 'address'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
             {'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
  'name': 'transferLockedFunds',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'uint256', 'name': 'lockIndex', 'type': 'uint256'}],
  'name': 'unlockFunds',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'components': [{'internalType': 'bytes32', 'name': 'chainId', 'type': 'bytes32'},
                             {'internalType': 'bytes', 'name': 'tokenAddress', 'type': 'bytes'},
                             {'internalType': 'string', 'name': 'ticker', 'type': 'string'}],
              'internalType': 'struct TokenInfo',
              'name': 'newTokenInfo',
              'type': 'tuple'}],
  'name': 'updateTokenInfo',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
  'name': 'usedSignatures',
 'outputs': [{'internalType': 'bool', 'name': 'used', 'type': 'bool'}],
 'stateMutability': 'view',
 'type': 'function'},
 {'inputs': [{'internalType': 'uint256', 'name': 'chainId', 'type': 'uint256'}],
  'name': 'getNonce',
  'outputs': [{'internalType': 'uint64', 'name': 'nonce', 'type': 'uint64'}],
  'stateMutability': 'view',
  'type': 'function'},
 {'inputs': [{'internalType': 'uint256', 'name': 'chainId', 'type': 'uint256'},
             {'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'}],
  'name': 'generateEVMNativeWithdrawal',
  'outputs': [{'internalType': 'bytes', 'name': 'output', 'type': 'bytes'}],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'uint256', 'name': 'chainId', 'type': 'uint256'},
             {'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'}],
  'name': 'generateEVMErc20Withdrawal',
  'outputs': [{'internalType': 'bytes', 'name': 'output', 'type': 'bytes'}],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'address', 'name': 'serviceAddress', 'type': 'address'},
             {'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'expiry', 'type': 'uint256'},
             {'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
  'name': 'verifyLockSignature',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'uint256', 'name': 'lockIndex', 'type': 'uint256'},
             {'internalType': 'address', 'name': 'toAddress', 'type': 'address'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
             {'internalType': 'address', 'name': 'serviceAddress', 'type': 'address'},
             {'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
  'name': 'verifyTransferLockedSignature',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'address', 'name': 'toAddress', 'type': 'address'},
             {'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
             {'internalType': 'uint256', 'name': 'expiry', 'type': 'uint256'},
             {'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
  'name': 'verifyTransferSignature',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'},
 {'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'},
             {'internalType': 'bytes32', 'name': 'tokenId', 'type': 'bytes32'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
             {'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
  'name': 'verifyWithdrawSignature',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function'}]
